#ifndef PROPS_BLOCK_GLSL
#define PROPS_BLOCK_GLSL
#if !defined(BLOCK_ID_MAPPING)
#define BLOCK_ID_MAPPING
// This file was automatically generated by block_wrangler


bool IsPlant(int id) {
	return id == 1000;
}


#endif // BLOCK_ID_MAPPING          
#endif
