#if !defined(PROPS_BLOCK_GLSL_INCLUDED)
#define PROPS_BLOCK_GLSL_INCLUDED
// This file was automatically generated by block_wrangler

bool bp_isPlant(int id) {
    return id == 1000;
}


#endif // PROPS_BLOCK_GLSL_INCLUDED